apiVersion: v1
kind: Secret
metadata:
  name: private-adi-repo
  namespace: openshift-gitops
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/adi-sharma14/aro-configs
  password: ${GITHUB_TOKEN}
  username: not-used