apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: s2iapp
  namespace: openshift-gitops
spec:
  destination:
    namespace: s2iapp
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      recurse: true
    path: s2iapp
    repoURL: https://github.com/adi-sharma14/aro-configs
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
